<?php
 return array(
    'barbershop' => array(
        'image'       =>  trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/barbershop-demo-image.jpg',
        'name'        => 'Barber Shop',
        'builder'     => 'Elementor',
        'homepage'    => 'Homepage Barbershop',
        'menu'        => 'Barbershop Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/barbershop/',
        'version'     => '5.0.1',
        'new'         => true,
    ),
    'real-house' => array(
        'image'       =>  trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/realhouse-demo-image.jpg',
        'name'        => 'Real House',
        'builder'     => 'Elementor',
        'homepage'    => 'HomePage RealHouse',
        'menu'        => 'RealHouse Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/realhouse/',
        'version'     => '5.0',
        'new'         => true,
    ),
    'scooter' => array(
        'image'       =>  trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/scooter-demo-image.jpg',
        'name'        => 'Scooter',
        'builder'     => 'Elementor',
        'homepage'    => 'Homepage Scooter',
        'menu'        => 'Scooter Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/scooter/',
        'version'     => '5.0',
        'new'         => true,
    ),
    'adventure' => array(
        'image'       =>  trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/adventure-demo-image.jpg',
        'name'        => 'Adventure',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Adventure',
        'menu'        => 'Adventure Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/adventure/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'app' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/app-demo-image.jpg',
        'name'        => 'App',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage APP',
        'menu'        => 'Mobile App Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/app/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'barber' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/barber-demo-image.jpg',
        'name'        => 'Barber',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Barber',
        'menu'        => 'Barber Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/barber/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'cloud-hosting' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/cloud-hosting-demo-image.jpg',
        'name'        => 'Cloud Hosting',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Cloud Hosting',
        'menu'        => 'Hosting Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/cloud-hosting/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'coffee-shop' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/coffee-shop-demo-image.jpg',
        'name'        => 'Coffee Shop',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Coffee Shop',
        'menu'        => 'Coffee Shop Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/coffee-shop/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'construction' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/construction-demo-image.jpg',
        'name'        => 'Construction',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Construction',
        'menu'        => 'Construction Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/construction/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'creative' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/creative-demo-image.jpg',
        'name'        => 'Creative',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Creative',
        'menu'        => 'Creative Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/creative/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'creative-v2' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/creative-v2-demo-image.jpg',
        'name'        => 'Creative V2',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Creative v2',
        'menu'        => 'Creative V2 Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/creative-v2/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'cupcake' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/cupcake-demo-image.jpg',
        'name'        => 'CupCake',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Cupcake',
        'menu'        => 'CupCake Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/cupcake/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'designer' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/designer-demo-image.jpg',
        'name'        => 'Designer',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Designer',
        'menu'        => 'Designer Main Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/designer/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'drone' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/drone-demo-image.jpg',
        'name'        => 'Drone',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Drone',
        'menu'        => 'Drone Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/drone/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'freelancer' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/freelancer-demo-image.jpg',
        'name'        => 'Freelancer',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Freelancer',
        'menu'        => 'Freelancer Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/freelancer/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'freelancer-portfolio' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/freelancer-portfolio-demo-image.jpg',
        'name'        => 'Freelancer Portfolio',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Freelancer Portfolio',
        'menu'        => 'Freelancer Portfolio Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/freelancer-portfolio/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'gym' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/gym-demo-image.jpg',
        'name'        => 'Gym',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Gym',
        'menu'        => 'Gym Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/gym/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'lawyer' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/lawyer-demo-image.jpg',
        'name'        => 'Lawyer',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Lawyer',
        'menu'        => 'Lawyer Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/lawyer/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'medical' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/medical-demo-image.jpg',
        'name'        => 'Medical',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Medical',
        'menu'        => 'Medical Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/medical/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'photography' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/photography-demo-image.jpg',
        'name'        => 'Photography',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Photography',
        'menu'        => 'Photography Main Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/photography/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'photography-v2' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/photography-v2-demo-image.jpg',
        'name'        => 'Photography V2',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Photography v2',
        'menu'        => 'Photography V2 Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/photography-v2/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'resume' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/resume-demo-image.jpg',
        'name'        => 'Resume',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Resume',
        'menu'        => 'Resume Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/resume/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'single-property' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/single-property-demo-image.jpg',
        'name'        => 'Single Property',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Single Property',
        'menu'        => 'Single Property Demo Main Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/single-property/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'tattoo' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/tattoo-demo-image.jpg',
        'name'        => 'Tattoo',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Tattoo',
        'menu'        => 'Tattoo Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/tattoo/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'taxi' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/taxi-demo-image.jpg',
        'name'        => 'Taxi',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Taxi',
        'menu'        => 'Taxi Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/taxi/',
        'version'     => '4.0',
        'new'         => false,
    ),
    'watch-shop' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/watch-shop-demo-image.jpg',
        'name'        => 'Watch Shop',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Watch Shop',
        'menu'        => 'Watches Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/watch-shop/',
        'version'     => '4.0',
        'new'         => false,
        'woocommerce' => array('shop' => 'Shop',
                      'cart'      => 'Cart',
                      'checkout'  => 'Checkout',
                      'myaccount' => 'My Account',
                    )
    ),
    'yoga' => array(
        'image'       => trailingslashit( plugin_dir_url( dirname( __FILE__ ) ) ).'demo-data/images/yoga-demo-image.jpg',
        'name'        => 'Yoga',
        'builder'     => 'WPBakery',
        'homepage'    => 'Homepage Yoga',
        'menu'        => 'Yoga Demo Menu',
        'preview'     => 'http://themes.webcreations907.com/ninezeroseven/yoga-studio/',
        'version'     => '4.0',
        'new'         => false,
    ),

);